### ISSUE TITLE
Display issues with {{date}}

### ISSUE THREAD

**Issue by math-feng** [mario-holubar/obsidian-daily-note-creator#1]
When the diary template has a date {{date}}, it is replaced with the format specified when the diary was created, e.g. YYYY/MMM/Wo/ddd. instead of the YYYY-MM-DD format, which is what is displayed when I create the diary manually.

**Comment by mario-holubar** [comment]
This is a problem with the `obsidian-daily-notes-interface` package. I've created an issue there: https://github.com/liamcain/obsidian-daily-notes-interface/issues/29

In the meantime, you can fix it by using `{{date:YYYY-MM-DD}}`
